### ISSUE TITLE
VIEWs are not supported

### ISSUE THREAD

**Issue by lordnynex** [sadasystems/gcsb#26]
Running a 100% READ workload against a view fails. There appears to be a nil pointer dereference immediately after schema detection. This is likely from an immediate `schema.GetTable()` call while comparing schema table to config. Need to add some sort of `IsView()` check to support this. Additionally, testing views should fail if the write fraction is > 0. 

```
gcsb run -t SingerNames -r 100 -w 0
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1703491]

goroutine 1 [running]:
github.com/sadasystems/gcsb/pkg/schema.NewTableFromSchema(0xc001003850, 0xc001003860, 0xc001003870, 0xc001003880, 0x0, 0x0, 0x0, 0xc000a93900, 0x16875f1)
	/Users/nynex/code/sada/google/gcsb/pkg/schema/table.go:108 +0x171
github.com/sadasystems/gcsb/pkg/schema.LoadTables.func1(0xc00041d0e0, 0xc00041d0e0, 0x0)
	/Users/nynex/code/sada/google/gcsb/pkg/schema/table.go:89 +0x109
cloud.google.com/go/spanner.(*RowIterator).Do(0xc000fac500, 0xc000a93a88, 0x0, 0x0)
	/Users/nynex/code/sada/google/gcsb/vendor/cloud.google.com/go/spanner/read.go:199 +0xa9
github.com/sadasystems/gcsb/pkg/schema.LoadTables(0x19e1038, 0xc000219940, 0xc00035c080, 0x19e35b8, 0xc00034a140, 0x0, 0x0)
	/Users/nynex/code/sada/google/gcsb/pkg/schema/table.go:83 +0x225
github.com/sadasystems/gcsb/pkg/schema.LoadSchema(0x19e1038, 0xc000219940, 0xc0003e46c0, 0x619ebbfb, 0xc00035fc00, 0x10cdb06, 0x619ebbfb)
	/Users/nynex/code/sada/google/gcsb/pkg/schema/schema.go:40 +0x153
github.com/sadasystems/gcsb/pkg/cmd.glob..func9.1()
	/Users/nynex/code/sada/google/gcsb/pkg/cmd/run.go:100 +0x52
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc00041c0c0, 0xc00041c0f0)
	/Users/nynex/code/sada/google/gcsb/vendor/github.com/rcrowley/go-metrics/timer.go:227 +0x4d
github.com/sadasystems/gcsb/pkg/cmd.glob..func9(0x1e51fa0, 0xc000141860, 0x0, 0x6)
	/Users/nynex/code/sada/google/gcsb/pkg/cmd/run.go:99 +0x456
github.com/spf13/cobra.(*Command).execute(0x1e51fa0, 0xc000141800, 0x6, 0x6, 0x1e51fa0, 0xc000141800)
	/Users/nynex/code/sada/google/gcsb/vendor/github.com/spf13/cobra/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1e51d20, 0xc000000180, 0x200000003, 0xc000000180)
	/Users/nynex/code/sada/google/gcsb/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nynex/code/sada/google/gcsb/vendor/github.com/spf13/cobra/command.go:902
github.com/sadasystems/gcsb/pkg/cmd.Execute()
	/Users/nynex/code/sada/google/gcsb/pkg/cmd/root.go:30 +0x31
main.main()
	/Users/nynex/code/sada/google/gcsb/main.go:6 +0x25
exit status 2
```

**Comment by lordnynex** [comment]
I've fixed the above panic. It is technically possible to execute a 100% READ run phase against a view table, but right now we throw an error because views do not have primary keys. We rely on primary keys to generate point reads. One possible option is to just take the the column int he first ordinal position and use it to generate reads. I'm unsure if this is some sort of anti-pattern though. 

For example, With the view 

```sql
CREATE VIEW SingerNames
SQL SECURITY INVOKER
AS SELECT
  Singers.SingerId AS SingerId,
  Singers.FirstName || " " || Singers.LastName AS Name
FROM Singers;
```

We end up with this out of the information schema 

```
(*schema.table)(0xc000244e00)({
 n: (string) (len=11) "SingerNames",
 t: (string) (len=4) "VIEW",
 p: (string) "",
 parent: (schema.Table) <nil>,
 spannerState: (string) "",
 columns: (*schema.columns)(0xc0000a1e00)({
  iteratorIndex: (int) 0,
  columns: ([]schema.Column) (len=2 cap=2) {
   (*schema.column)(0xc000c38400)({
    name: (string) (len=8) "SingerId",
    position: (int64) 1,
    nullable: (string) (len=3) "YES",
    spannerType: (string) (len=5) "INT64",
    isGenerated: (bool) false,
    generationExpression: (string) "",
    isStored: (string) "",
    spannerState: (string) (len=9) "COMMITTED",
    primaryKey: (bool) false
   }),
   (*schema.column)(0xc000c38500)({
    name: (string) (len=4) "Name",
    position: (int64) 2,
    nullable: (string) (len=3) "YES",
    spannerType: (string) (len=11) "STRING(MAX)",
    isGenerated: (bool) false,
    generationExpression: (string) "",
    isStored: (string) "",
    spannerState: (string) (len=9) "COMMITTED",
    primaryKey: (bool) false
   })
  }
 }),
 indexes: (*schema.indexes)(0xc0000a1e20)({
  iteratorIndex: (int) 0,
  indexes: ([]schema.Index) {
  }
 })
})
```

In this case, Singer ID is a perfectly valid for generating point reads from this view. I'm unsure if this approach is ok with views that have a pseudo composite key. Meaning a view consisting of multiple primary keys from different tables via a join.
